/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f0f3ff',
        'secondary-fixed-dim': '#bbc3ff',
        'tertiary-container': '#002320',
        'error-container': '#ffdad6',
        'inverse-primary': '#c0c1ff',
        'on-tertiary-fixed': '#00201d',
        'surface-bright': '#f9f9ff',
        'on-primary-fixed-variant': '#3d4083',
        secondary: '#4e599e',
        'surface-container': '#e6eeff',
        outline: '#777681',
        'on-primary': '#ffffff',
        'secondary-fixed': '#dee0ff',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#00315e',
        'on-secondary-container': '#364285',
        'surface-tint': '#55589c',
        'tertiary-fixed-dim': '#69d8cd',
        'outline-variant': '#c7c5d2',
        'surface-dim': '#c6dbff',
        surface: '#f9f9ff',
        'on-surface-variant': '#464650',
        tertiary: '#000605',
        primary: '#010025',
        'on-primary-fixed': '#0f1056',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#a6b1fd',
        background: '#f9f9ff',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'on-primary-container': '#7d7fc7',
        'tertiary-fixed': '#86f5ea',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#d4e3ff',
        'primary-container': '#121358',
        'inverse-on-surface': '#ebf1ff',
        'on-surface': '#001c3a',
        'on-secondary-fixed-variant': '#354185',
        'surface-variant': '#d4e3ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-background': '#001c3a',
        'on-tertiary-container': '#08968d',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#031158',
        'surface-container-high': '#dde9ff',
        'primary-fixed': '#e1e0ff',
        'on-tertiary-fixed-variant': '#00504b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-md': '0.75rem',
        'margin-mobile': '1rem',
        gutter: '1rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
        'space-sm': '0.5rem',
        margin: '1.5rem',
        'gutter-compact': '0.5rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'body-sm': ['Hanken Grotesk'],
        'label-sm': ['Hanken Grotesk'],
        'body-lg': ['Hanken Grotesk'],
        'data-code': ['JetBrains Mono'],
        'label-md': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'headline-lg': ['Hanken Grotesk'],
        'body-md': ['Hanken Grotesk'],
        'display-lg-mobile': ['Hanken Grotesk'],
        'data-metric': ['JetBrains Mono'],
        'display-lg': ['Hanken Grotesk'],
        'label-lg': ['Hanken Grotesk'],
        'headline-sm': ['Hanken Grotesk'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-code': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'data-metric': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}