/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#EFF3F9',
        'secondary-fixed-dim': '#AFC6E3',
        'tertiary-container': '#002320',
        'error-container': '#ffdad6',
        'inverse-primary': '#A8C4EA',
        'on-tertiary-fixed': '#00201d',
        'surface-bright': '#F7F9FC',
        'on-primary-fixed-variant': '#2E4E7E',
        secondary: '#33598F',
        'surface-container': '#E4EBF4',
        outline: '#6F7C8F',
        'on-primary': '#ffffff',
        'secondary-fixed': '#D8E4F5',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#1D2B40',
        'on-secondary-container': '#1C3A66',
        'surface-tint': '#3D5C8C',
        'tertiary-fixed-dim': '#69d8cd',
        'outline-variant': '#C1CEDD',
        'surface-dim': '#C8D6E8',
        surface: '#F7F9FC',
        'on-surface-variant': '#445064',
        tertiary: '#000605',
        primary: '#0A1E3F',
        'on-primary-fixed': '#001830',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#A9C4E8',
        background: '#F7F9FC',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'on-primary-container': '#A8C7F0',
        'tertiary-fixed': '#86f5ea',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#CEDBEA',
        'primary-container': '#123B6D',
        'inverse-on-surface': '#EFF3F9',
        'on-surface': '#0C1B30',
        'on-secondary-fixed-variant': '#22406B',
        'surface-variant': '#CEDBEA',
        'primary-fixed-dim': '#A8C4EA',
        'on-background': '#0C1B30',
        'on-tertiary-container': '#08968d',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#0A1D38',
        'surface-container-high': '#D9E3EF',
        'primary-fixed': '#D4E2F5',
        'on-tertiary-fixed-variant': '#00504b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-md': '0.75rem',
        'margin-mobile': '1rem',
        gutter: '1rem',
        'space-lg': '1.25rem',
        'space-xl': '2rem',
        'space-sm': '0.5rem',
        margin: '1.5rem',
        'gutter-compact': '0.5rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'body-sm': ['Hanken Grotesk'],
        'label-sm': ['Hanken Grotesk'],
        'body-lg': ['Hanken Grotesk'],
        'data-code': ['JetBrains Mono'],
        'label-md': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'headline-lg': ['Hanken Grotesk'],
        'body-md': ['Hanken Grotesk'],
        'display-lg-mobile': ['Hanken Grotesk'],
        'data-metric': ['JetBrains Mono'],
        'display-lg': ['Hanken Grotesk'],
        'label-lg': ['Hanken Grotesk'],
        'headline-sm': ['Hanken Grotesk'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-code': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'data-metric': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}